HSG.Warehouse.Web/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HSG.Warehouse.Web.ViewModels
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Введіть дані")]
        public string? Login { get; set; }
        [Required(ErrorMessage = "Введіть дані")]
        public string? Password { get; set; }
        public bool RememberMe { get; set; }        
    }
}

HSG.Warehouse.Web/Controllers/InvoiceController.cs
using HSG.Warehouse.Common.Models;
using HSG.Warehouse.Common.Models.Entity;
using HSG.Warehouse.Interfaces.Repository;
using HSG.Warehouse.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HSG.Warehouse.Web.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        private readonly IInvoicesRepository _invoicesRepository;
        private readonly IOptionsRepository _optionsRepository;

        public InvoiceController(IInvoicesRepository invoicesRepository, IOptionsRepository optionsRepository)
        {
            _invoicesRepository = invoicesRepository;
            _optionsRepository = optionsRepository;
        }
        public async Task<IActionResult> Index()
        {
            var vm = new InvoicesListViewModel();
            vm.Invoices = await _invoicesRepository.GetAllAsync();

            return View(vm);
        }
        public async Task<IActionResult> Create()
        {
            var vm = new InvoiceViewModel();
            vm.Currencys = await _optionsRepository.GetAllCurrencyAsync();
            vm.Clients = await _optionsRepository.GetAllClientsAsync();

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Create(Invoice invoice)
        {            
            var error = await _invoicesRepository.CreateAsync(invoice);

            if (invoice.Id > 0)
            {
                return LocalRedirect("~/Invoice/AddProduct?CategoryId=0&InvoiceId=" + @invoice.Id);
            }

            var vm = new InvoiceViewModel();
            vm.Currencys = await _optionsRepository.GetAllCurrencyAsync();
            vm.Clients = await _optionsRepository.GetAllClientsAsync();

            TempData["Error"] = error;
            return View(vm);
        }
        public async Task<IActionResult> Edit(int invoiceId)
        {
            //Роблю перевірку чи є такий інвойс і чи він не "зафіксований"
            var invoiceStatus = await _invoicesRepository.GetSatusAsync(invoiceId);

            switch (invoiceStatus)
            {
                case 1:
                    TempData["Error"] = "Накладна зафіксована. Редагування заборонено!";
                    return RedirectToAction("Index");

                case 2:
                    TempData["Error"] = "Нема даних!";
                    return RedirectToAction("Index");
            }

            var vm = new InvoiceViewModel();
            vm.Invoice = await _invoicesRepository.GetByIdAsync(invoiceId);
            vm.Currencys = await _optionsRepository.GetAllCurrencyAsync();
            vm.Clients = await _optionsRepository.GetAllClientsAsync();

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Invoice invoice)
        {
            //Роблю перевірку чи є такий інвойс і чи він не "зафіксований"

            if (invoice.Id > 0)
            {
                var invoiceStatus = await _invoicesRepository.GetSatusAsync(invoice.Id);

                switch (invoiceStatus)
                {
                    case 0:
                        var result = await _invoicesRepository.EditAsync(invoice);
                        if (result != null)
                        {
                            TempData["Error"] = result;
                        }
                        else
                        {
                            return RedirectToAction("Index");
                        }
                        break;
                    case 1:
                        TempData["Error"] = "Накладна зафіксована. Редагування заборонено!";
                        break;
                    case 2:
                        TempData["Error"] = "Нема даних!";
                        break;
                }
            }
            var vm = new InvoiceViewModel();
            vm.Invoice = invoice;
            vm.Currencys = await _optionsRepository.GetAllCurrencyAsync();
            vm.Clients = await _optionsRepository.GetAllClientsAsync();

            return View(vm);
        }
        public async Task<IActionResult> AddProduct(int categoryId, int invoiceId)
        {
            //Роблю перевірку чи є такий інвойс і чи він не "зафіксований"
            var invoiceStatus = await _invoicesRepository.GetSatusAsync(invoiceId);

            if (invoiceStatus != 0)
            {
                TempData["Error"] = "Нема даних!";
                return RedirectToAction("Index");
            }

            var categories = await _optionsRepository.GetAllCategoriesAsync();

            var vm = new ProductToInvoiceViewModel();
            vm.Categories = categories;
            vm.ProductToInvoices = await _invoicesRepository.GetProductToInvoices(categoryId, invoiceId);
            vm.Invoice = await _invoicesRepository.GetByIdAsync(invoiceId);
            vm.Sum = await _invoicesRepository.GetSumByIdAsync(invoiceId);

            vm.CategoryMenu = new CategoryMenu
            {
                SelectedId = categoryId,
                Categories = categories,
            };

            var path = HttpContext.Request.QueryString.ToString();
            vm.CategoryMenu.QueryString = path.Remove(0, path.IndexOf("&"));

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> AddProduct(InvoiceDetail invoiceDetail)
        {
            var error = await _invoicesRepository.AddProductAsync(invoiceDetail);
            var sum = await _invoicesRepository.GetSumByIdAsync(invoiceDetail.InvoiceId);

            return error == null ? Ok(sum) : NotFound();
        }
        public async Task<IActionResult> View(int invoiceId)
        {
            var vm = new InvoiceViewViewModel();
            vm.Invoice = await _invoicesRepository.GetByIdAsync(invoiceId);
            vm.InvoiceDetail = await _invoicesRepository.GetAllProductsFromInvoiceAsync(invoiceId);
            vm.Sum = await _invoicesRepository.GetSumByIdAsync(invoiceId);
            return View(vm);
        }
        public async Task<IActionResult> Delete(int invoiceId)
        {
            TempData["Error"] = await _invoicesRepository.DeleteAsync(invoiceId);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteProduct(InvoiceDetail invoiceDetail)
        {
            var result = await _invoicesRepository.DeleteProductAsync(invoiceDetail);
            var sum = await _invoicesRepository.GetSumByIdAsync(invoiceDetail.InvoiceId);

            return result == null ? Ok(sum) : NotFound();
        }
        public async Task<IActionResult> Save(Invoice invoice)
        {
            var result = await _invoicesRepository.SaveAsync(invoice.Id);

            if (result == null)
            {
                return RedirectToAction("Index");
            }

            TempData["Error"] = result;

            return RedirectToAction("View", new { id = invoice.Id });
        }
    }
}

HSG.Warehouse.Web/Controllers/SaleController.cs
using HSG.Warehouse.Common.Models;
using HSG.Warehouse.Common.Models.Entity;
using HSG.Warehouse.Interfaces.Repository;
using HSG.Warehouse.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HSG.Warehouse.Web.Controllers
{
    [Authorize]
    public class SaleController : Controller
    {
        private readonly ISalesRepository _salesRepository;
        private readonly IOptionsRepository _optionsRepository;
        private readonly IWarehouseRepository _warehouseRepository;

        public SaleController(ISalesRepository salesRepository, IOptionsRepository optionsRepository, IWarehouseRepository warehouseRepository)
        {
            _salesRepository = salesRepository;
            _optionsRepository = optionsRepository;
            _warehouseRepository = warehouseRepository;
        }
        public async Task<IActionResult> Index()
        {
            var vm = new SalesListViewModel();
            vm.Sales = await _salesRepository.GetAllAsync();

            return View(vm);
        }
        public async Task<IActionResult> Create()
        {
            var vm = new SaleViewModel();
            vm.Currencys = await _optionsRepository.GetAllCurrencyAsync();
            vm.Clients = await _optionsRepository.GetAllClientsAsync();

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Create(Sale sale)
        {
            var error = await _salesRepository.CreateAsync(sale);

            if (sale.Id > 0)
            {
                return LocalRedirect("~/Sale/AddProduct?CategoryId=0&SaleId=" + sale.Id);
            }

            var vm = new SaleViewModel();
            vm.Currencys = await _optionsRepository.GetAllCurrencyAsync();
            vm.Clients = await _optionsRepository.GetAllClientsAsync();

            TempData["Error"] = error;
            return View(vm);
        }
        public async Task<IActionResult> AddProduct(int categoryId, int saleId)
        {

            //Роблю перевірку чи є така накладна і чи вона не "зафіксована"
            var saleStatus = await _salesRepository.GetSatusAsync(saleId);

            if (saleStatus != 0)
            {
                TempData["Error"] = "Нема даних!";
                return RedirectToAction("Index");
            }

            var vm = new WarehouseViewModel();
            vm.Warehouse = await _warehouseRepository.GetProductsAsync(categoryId, 0);
            var categories = await _optionsRepository.GetAllCategoriesAsync();
            vm.ProductToSales = await _salesRepository.GetProductsForSaleAsync(categoryId, saleId);
            vm.Sale = await _salesRepository.GetByIdAsync(saleId);
            vm.Sum = await _salesRepository.GetSumByIdAsync(saleId);
            vm.Categories = categories;
            vm.CategoryMenu = new CategoryMenu
            {
                SelectedId = categoryId,
                Categories = categories
            };

            var path = HttpContext.Request.QueryString.ToString();
            vm.CategoryMenu.QueryString = path.Remove(0, path.IndexOf("&"));

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> AddProduct(SaleDetail saleDetail)
        {
            var error = await _salesRepository.AddProductAsync(saleDetail);
            var sum = await _salesRepository.GetSumByIdAsync(saleDetail.SaleId);

            return error == null ? Ok(sum) : NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> DeleteProduct(int saleDetailId, int saleId)
        {
            var error = await _salesRepository.DeleteProductAsync(saleDetailId);
            var sum = await _salesRepository.GetSumByIdAsync(saleId);

            return error == null ? Ok(sum) : NotFound();
        }
        public async Task<IActionResult> Delete(int saleId)
        {
            TempData["Error"] = await _salesRepository.DeleteAsync(saleId);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Save(Sale sale)
        {
            var result = await _salesRepository.SaveAsync(sale.Id);

            if (result == null)
            {
                return RedirectToAction("Index");
            }

            TempData["Error"] = result;

            return LocalRedirect($"~/Sale/AddProduct?CategoryId=0&SaleId={sale.Id}");
        }
        public async Task<IActionResult> View(int saleId)
        {
            var vm = new SaleViewViewModel();
            vm.Sale = await _salesRepository.GetByIdAsync(saleId);
            vm.SaleDetail = await _salesRepository.GetAllProductsFromSaleAsync(saleId);
            vm.Sum = await _salesRepository.GetSumByIdAsync(saleId);
            return View(vm);
        }

        public async Task<IActionResult> Edit(int saleId)
        {
            //Роблю перевірку чи є така накладна і чи вона не зафіксована
            var saleStatus = await _salesRepository.GetSatusAsync(saleId);

            switch (saleStatus)
            {
                case 1:
                    TempData["Error"] = "Накладна зафіксована. Редагування заборонено!";
                    return RedirectToAction("Index");

                case 2:
                    TempData["Error"] = "Нема даних!";
                    return RedirectToAction("Index");
            }

            var vm = new SaleViewModel();
            vm.Sale = await _salesRepository.GetByIdAsync(saleId);
            vm.Currencys = await _optionsRepository.GetAllCurrencyAsync();
            vm.Clients = await _optionsRepository.GetAllClientsAsync();

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Sale sale)
        {
            //Роблю перевірку чи є така накладна і чи вона не зафіксована

            if (sale.Id > 0)
            {
                var saleStatus = await _salesRepository.GetSatusAsync(sale.Id);

                switch (saleStatus)
                {
                    case 0:
                        var result = await _salesRepository.EditAsync(sale);
                        if (result != null)
                        {
                            TempData["Error"] = result;
                        }
                        else
                        {
                            return RedirectToAction("Index");
                        }
                        break;
                    case 1:
                        TempData["Error"] = "Накладна зафіксована. Редагування заборонено!";
                        break;
                    case 2:
                        TempData["Error"] = "Нема даних!";
                        break;
                }
            }
            var vm = new SaleViewModel();
            vm.Sale = sale;
            vm.Currencys = await _optionsRepository.GetAllCurrencyAsync();
            vm.Clients = await _optionsRepository.GetAllClientsAsync();

            return View(vm);

        }
    }
}

HSG.Warehouse.Web/Controllers/WarehouseController.cs
using HSG.Warehouse.Common.Models;
using HSG.Warehouse.Common.Models.Entity;
using HSG.Warehouse.Interfaces.Repository;
using HSG.Warehouse.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HSG.Warehouse.Web.Controllers
{
    [Authorize]
    public class WarehouseController : Controller
    {
        private readonly IWarehouseRepository _warehouseRepository;
        private readonly IOptionsRepository _optionsRepository;

        public WarehouseController(IWarehouseRepository warehouseRepository, IOptionsRepository optionsRepository)
        {
            _warehouseRepository = warehouseRepository;
            _optionsRepository = optionsRepository;
        }
        public async Task<IActionResult> Index(int categoryId)
        {
            int currencId = 0;
            var vm = new WarehouseViewModel();
            vm.Warehouse = await _warehouseRepository.GetProductsAsync(categoryId, currencId);
            var categories = await _optionsRepository.GetAllCategoriesAsync();
            vm.Categories = categories;
            vm.CategoryMenu = new CategoryMenu
            {
                SelectedId = categoryId,
                Categories = categories
            };
            //vm.seededCategories.QueryString = HttpContext.Request.QueryString.ToString();

            return View(vm);
        }
    }
}

HSG.Warehouse.Web/Views/Shared/_CategoryDropDownList.cshtml
@model CategoryMenu
@*@model SeededCategories*@


@if (Model.Categories.OrderBy(c => c.Name).Any())
{
    var controller = @ViewContext.RouteData.Values["controller"];
    var action = @ViewContext.RouteData.Values["action"];

    <select id="SelectCatetegoryId" name="CatetegoryId" class="form-control border-input">
        <option value=0>Всі категорії</option>

        @foreach (var category in Model.Categories)
        {
            if (category.Id == Model.SelectedId)
            {
                <option value=@category.Id selected>@category.Name</option>
            }
            else
            {
                <option value=@category.Id>@category.Name</option>
            }
        }
    </select>
    <script>
        let select = document.getElementById('SelectCatetegoryId');
        select.addEventListener('change', function () {
            let url = '/@controller/@action?CategoryId=' + select.value + "@Model.QueryString";
            url = url.replace(/&amp;/g, "&");            
            location = url;
        });
    </script>

}

HSG.Warehouse.Web/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Складський облік</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Animation library for notifications   -->
    <link href="~/assets/css/animate.min.css" rel="stylesheet" />
    <!--  Paper Dashboard core CSS    -->
    <link href="~/assets/css/paper-dashboard.css" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project   -->
    <link href="~/assets/css/demo.css" rel="stylesheet" />

    <!--  Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="~/assets/css/themify-icons.css" rel="stylesheet">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

    <div class="wrapper">
        <div class="sidebar" data-background-color="white" data-active-color="danger">

            <!--
                Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
                Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
            -->

            <div class="sidebar-wrapper">
                <div class="logo">
                    @*<a href="http://www.creative-tim.com" class="simple-text">*@
                    <h3>Складський облік</h3>
                    @*</a>*@
                </div>
                <ul class="nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li id="liPanel">
                            <a asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="ti-stats-up"></i>
                                <p>Статистика</p>
                            </a>
                        </li>
                        <li id="liOptions">
                            <a asp-area="" asp-controller="Options" asp-action="Index">
                                <i class="ti-settings"></i>
                                <p>Налаштування</p>
                            </a>
                        </li>
                        <li id="liInvoice">
                            <a asp-area="" asp-controller="Invoice" asp-action="Index">
                                <i class="ti-import"></i>
                                <p>Приход</p>
                            </a>
                        </li>
                        <li id="liSale">
                            <a asp-area="" asp-controller="Sale" asp-action="Index">
                                <i class="ti-export"></i>
                                <p>Продаж</p>
                            </a>
                        </li>
                        <li id="liWarehouse">
                            <a asp-area="" asp-controller="Warehouse" asp-action="Index">
                                <i class="ti-package"></i>
                                <p>Склад</p>
                            </a>
                        </li>
                        <li id="liExit">
                            <a asp-area="" asp-controller="Home" asp-action="Logout">
                                <i class="ti-shift-right"></i>
                                <p>Вихід</p>
                            </a>
                        </li>
                    }
                    else
                    {
                        await Html.RenderPartialAsync("_Login");
                    }
                </ul>
            </div>
        </div>

        <div class="main-panel">
            @if (User.Identity.IsAuthenticated)
            {
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar bar1"></span>
                                <span class="icon-bar bar2"></span>
                                <span class="icon-bar bar3"></span>
                            </button>
                            @*<a class="navbar-brand" href="#">Dashboard</a>*@
                        </div>
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a asp-controller="Home" asp-action="Index">
                                        <i class="ti-stats-up"></i>
                                        <p>Статистика</p>
                                    </a>
                                </li>
                                @*                            <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="ti-bell"></i>
                            <p class="notification">5</p>
                            <p>Notifications</p>
                            <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                            <li><a href="#">Notification 1</a></li>
                            <li><a href="#">Notification 2</a></li>
                            <li><a href="#">Notification 3</a></li>
                            <li><a href="#">Notification 4</a></li>
                            <li><a href="#">Another notification</a></li>
                            </ul>
                            </li>*@
                                <li>
                                    <a asp-controller="Options" asp-action="Index">
                                        <i class="ti-settings"></i>
                                        <p>Налаштування</p>
                                    </a>
                                </li>
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li>
                                        <a asp-controller="Home" asp-action="Logout">
                                            <i class="ti-shift-right"></i>
                                            <p>Вихід</p>
                                        </a>
                                    </li>
                                }
                            </ul>

                        </div>
                    </div>
                </nav>
            }
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid">
                </div>
            </footer>

        </div>
    </div>
    @await RenderSectionAsync("Scripts", required: false)
</body>

<!--   Core JS Files   -->
<script src="~/assets/js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="~/assets/js/bootstrap.min.js" type="text/javascript"></script>

<!--  Checkbox, Radio & Switch Plugins -->
<script src="~/assets/js/bootstrap-checkbox-radio.js"></script>

<!--  Charts Plugin -->
<script src="~/assets/js/chartist.min.js"></script>

<!--  Notifications Plugin    -->
<script src="~/assets/js/bootstrap-notify.js"></script>

<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

<!-- Paper Dashboard Core javascript and methods for Demo purpose -->
<script src="~/assets/js/paper-dashboard.js"></script>



<!-- Paper Dashboard DEMO methods, don't include it in your project! -->
<script src="~/assets/js/demo.js"></script>

@*Для каталогу (TreeView)*@
<script src="~/js/site.js" asp-append-version="true"></script>

<script type="text/javascript">
    $(document).ready(function () {
    @{
        var controller = @ViewContext.RouteData.Values["controller"];
        string selectLi = "liInvoice";
        switch (controller.ToString().ToLower())
        {
            case "invoice":
                selectLi = "liInvoice";
                break;
            case "sale":
                selectLi = "liSale";
                break;
            case "options":
                selectLi = "liOptions";
                break;
            case "warehouse":
                selectLi = "liWarehouse";
                break;
            default:
                selectLi = "liPanel";
                break;
        }
    };
    });
    document.getElementById('@selectLi').className = "active";

</script>

</html>

HSG.Warehouse.Web/Views/Shared/_Login.cshtml
<form asp-controller="Home" asp-action="Login" method="post">


    <div class="content" style="margin:4px">
        @if (TempData["Error"] != null)
        {
            <div class="col-md-12 alert alert-danger">
                <span><b>Помилка!</b> - @TempData["Error"] </span>
            </div>
        }
        <label>Логін</label>
        <input type="text" name="login" class="form-control border-input" placeholder="Admin">
        <label>Пароль</label>
        <input type="password" name="password" class="form-control border-input" placeholder="Admin">
        <label>
            <input type="checkbox" id="rememberMe" name="rememberMe"> Зберегти дані
        </label>

        <div class="footer  text-center">
            <hr />
            <div class="numbers  text-center">
                <div class="text-center">
                    <button type="submit" class="btn btn-info btn-fill btn-wd">Вхід</button>
                </div>
                <div class="clearfix"></div>

            </div>
        </div>
    </div>


</form>