HSG.Warehouse.Web/ViewModels/WarehouseViewModel.cs
using HSG.Warehouse.Common.Models;
using HSG.Warehouse.Common.Models.Entity;

namespace HSG.Warehouse.Web.ViewModels
{
    public class WarehouseViewModel
    {
        public Sale? Sale { get; set; }
        public IEnumerable<Common.Models.Entity.Warehouse?>? Warehouse { get; set; }
        public IEnumerable<ProductForSale?>? ProductToSales { get; set; }// Для додавання товару у накладній відпуску
        public Currency? Currency { get; set; }
        public Unit? Unit { get; set; }
        public IEnumerable<Category?>? Categories { get; set; }
        public CategoryMenu? CategoryMenu { get; set; }
        public IEnumerable<SaleDetail?>? SaleDetails { get; set; }
        public double? Sum { get; set; }

    }
}

HSG.Warehouse.Web/Controllers/OptionsController.cs
using HSG.Warehouse.ClientServices.NbuCurrency;
using HSG.Warehouse.Common.Models;
using HSG.Warehouse.Common.Models.Entity;
using HSG.Warehouse.Interfaces;
using HSG.Warehouse.Interfaces.Repository;
using HSG.Warehouse.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HSG.Warehouse.Web.Controllers
{
    [Authorize]
    public class OptionsController : Controller
    {
        //private readonly AppDbContext _context;
        private readonly IOptionsRepository _optionsRepository;
        private readonly INbuCurrencyServiceClient _currencyApi;

        public OptionsController(IOptionsRepository optionsRepository, INbuCurrencyServiceClient nbuCurrency)
        {
            //_context = context;
            _optionsRepository = optionsRepository;
            _currencyApi = nbuCurrency;

        }

        public IActionResult Index()
        {
            return View();
        }

        #region ОДИНИЦІ ВИМІРУ
        public async Task<IActionResult> Units(int unitId)
        {
            var vm = new UnitViewModel();
            vm.Units = await _optionsRepository.GetAllUnitsAsync();
            vm.Unit = await _optionsRepository.GetUnitByIdAsync(unitId);

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> AddUnit(Unit unit)
        {
            TempData["Error"] = await _optionsRepository.AddUnitAsync(unit);
            return RedirectToAction("Units");
        }
        public async Task<IActionResult> EditUnit(Unit unit)
        {
            TempData["Error"] = await _optionsRepository.EditUnitAsync(unit); ;
            return RedirectToAction("Units");
        }
        public async Task<IActionResult> DeleteUnit(int unitId)
        {
            TempData["Error"] = await _optionsRepository.DeleteUnitAsync(unitId);

            return RedirectToAction("Units");
        }
        #endregion
        #region ВИРОБНИКИ / БРЕНДИ
        public async Task<IActionResult> Manufacturer(int manufacturerId)
        {
            var vm = new ManufacturerViewModel();
            vm.Manufacturer = await _optionsRepository.GetManufacturerByIdAsync(manufacturerId);
            vm.Manufacturers = await _optionsRepository.GetAllManufacturerAsync();

            return View(vm);
        }
        public async Task<IActionResult> AddManufacturer(Manufacturer manufacturer)
        {
            TempData["Error"] = await _optionsRepository.AddManufacturerAsync(manufacturer);

            return RedirectToAction("Manufacturer");
        }
        public async Task<IActionResult> EditManufacturer(Manufacturer manufacturer)
        {
            TempData["Error"] = await _optionsRepository.EditManufacturerAsync(manufacturer);

            return RedirectToAction("Manufacturer");
        }
        public async Task<IActionResult> DeleteManufacturer(int manufacturerId)
        {
            TempData["Error"] = await _optionsRepository.DeleteManufacturerAsync(manufacturerId);
            return RedirectToAction("Manufacturer");
        }
        #endregion
        #region КАТЕГОРІЇ
        public async Task<IActionResult> Category(int categoryId)
        {
            var vm = new CategoryViewModel();
            vm.Categories = await _optionsRepository.GetAllCategoriesAsync();
            vm.Category = await _optionsRepository.GetCategoryByIdAsync(categoryId);

            return View(vm);
        }
        public async Task<IActionResult> DeleteCategory(int categoryId)
        {
            TempData["Error"] = await _optionsRepository.DeleteCategoryAsync(categoryId); ;
            return RedirectToAction("Category");
        }
        public async Task<IActionResult> EditCategory(Category category)
        {
            TempData["Error"] = await _optionsRepository.EditCategoryAsync(category); ;

            return RedirectToAction("Category");
        }
        public async Task<IActionResult> AddCategory(Category category)
        {
            TempData["Error"] = await _optionsRepository.AddCategoryAsync(category);

            return RedirectToAction("Category");
        }

        #endregion
        #region ПРОДУКЦІЯ 
        public async Task<IActionResult> ProductsList(int categoryId)
        {
            var categories = await _optionsRepository.GetAllCategoriesAsync();
            var vm = new ProductsListViewModel();
            vm.Categories = categories;
            vm.Products = await _optionsRepository.GetProductsFromCategoryAsync(categoryId);

            vm.CategoryMenu = new CategoryMenu
            {
                SelectedId = categoryId,
                Categories = categories,
            };
           
            return View(vm);

        }
        public async Task<IActionResult> Product(int productId)
        {
            //_optionsRepository.GenerateBarcode();
            var vm = new ProductViewModel();
            vm.Categories = await _optionsRepository.GetAllCategoriesAsync();
            vm.Manufacturers = await _optionsRepository.GetAllManufacturerAsync();
            vm.Units = await _optionsRepository.GetAllUnitsAsync();
            vm.Product = await _optionsRepository.GetProductByIdAsync(productId);

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Product(ProductViewModel productViewModel)
        {
            var product = productViewModel.Product;

            string? error = null;
            // 0 - Створення нового товару
            if (productViewModel.Product?.Id == 0)
            {
                error = await _optionsRepository.AddProductAsync(product, productViewModel.IsAutoBarcode);
            }
            else
            {
                error = await _optionsRepository.EditProductAsync(product);
            }

            if (error == null)
            {
                return RedirectToAction("ProductsList");
            }

            productViewModel.Categories = await _optionsRepository.GetAllCategoriesAsync();
            productViewModel.Manufacturers = await _optionsRepository.GetAllManufacturerAsync();
            productViewModel.Units = await _optionsRepository.GetAllUnitsAsync();

            TempData["Error"] = error;
            return View(productViewModel);
        }
        public async Task<IActionResult> DeleteProduct(int productId)
        {
            TempData["Error"] = await _optionsRepository.DeleteProductAsync(productId);
            return RedirectToAction("ProductsList");
        }
        #endregion
        #region ВАЛЮТА
        public async Task<IActionResult> Currency(DateTime dateTime)
        {
            var value = _currencyApi.GetCurrencyOnDateAsync(DateTime.Now);
            var vm = new CurrencyViewModel();

            vm.Currency = await _optionsRepository.GetAllCurrencyAsync();

            dateTime = DateTime.Now;
            vm.CurrencyNBU = await _currencyApi.GetCurrencyOnDateAsync(dateTime);
            return View(vm);
        }
        public async Task<IActionResult> DeleteCurrency(int currencyId)
        {
            TempData["Error"] = await _optionsRepository.DeleteCurrencyAsync(currencyId);
            return RedirectToAction("Currency");
        }
        public async Task<IActionResult> AddCurrency(int currencyId)
        {
            //Отримую дазі з сайту НБУ
            var currencyList = await _currencyApi.GetCurrencyOnDateAsync(DateTime.Now);
            var currency = currencyList?.Where(c => c?.Code == currencyId).FirstOrDefault();

            TempData["Error"] = await _optionsRepository.AddCurrencyAsync(currency);

            return RedirectToAction("Currency");
        }
        #endregion
        #region КЛІЄНТИ
        public async Task<IActionResult> ClientsList()
        {
            var vm = new ClientsListViewModel();
            vm.Clients = await _optionsRepository.GetAllClientsAsync();

            return View(vm);
        }
        public async Task<IActionResult> Client(int clientId)
        {
            var client = new Client();
            client = await _optionsRepository.GetClientByIdAsync(clientId);

            return View(client);
        }
        [HttpPost]
        public async Task<IActionResult> AddClient(Client client)
        {
            TempData["Error"] = await _optionsRepository.AddClientAsync(client);
            return RedirectToAction("ClientsList");
        }
        [HttpPost]
        public async Task<IActionResult> EditClient(Client client)
        {
            TempData["Error"] = await _optionsRepository.EditClientAsync(client);
            return RedirectToAction("ClientsList");
        }
        public async Task<IActionResult> DeleteClient(int clientId)
        {
            TempData["Error"] = await _optionsRepository.DeleteClientAsync(clientId);
            return RedirectToAction("ClientsList");
        }
        #endregion
    }
}

HSG.Warehouse.Web/Controllers/WarehouseController.cs
using HSG.Warehouse.Common.Models;
using HSG.Warehouse.Common.Models.Entity;
using HSG.Warehouse.Interfaces.Repository;
using HSG.Warehouse.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HSG.Warehouse.Web.Controllers
{
    [Authorize]
    public class WarehouseController : Controller
    {
        private readonly IWarehouseRepository _warehouseRepository;
        private readonly IOptionsRepository _optionsRepository;

        public WarehouseController(IWarehouseRepository warehouseRepository, IOptionsRepository optionsRepository)
        {
            _warehouseRepository = warehouseRepository;
            _optionsRepository = optionsRepository;
        }
        public async Task<IActionResult> Index(int categoryId)
        {
            int currencId = 0;
            var vm = new WarehouseViewModel();
            vm.Warehouse = await _warehouseRepository.GetProductsAsync(categoryId, currencId);
            var categories = await _optionsRepository.GetAllCategoriesAsync();
            vm.Categories = categories;
            vm.CategoryMenu = new CategoryMenu
            {
                SelectedId = categoryId,
                Categories = categories
            };
            //vm.seededCategories.QueryString = HttpContext.Request.QueryString.ToString();

            return View(vm);
        }
    }
}

HSG.Warehouse.Web/Views/Warehouse/AddProduct.cshtml
@model ProductToInvoiceViewModel

<form method="post" asp-action="SaveInvoice" enctype="multipart/form-data">    
    <input type="hidden" asp-for="Invoice.Id" />
    <div class="card">
        @*Хлібні крошки*@
        @*    <div>
        @{
        await Html.RenderPartialAsync("_NavMenu", Model.seededCategories);
        }
        </div>*@

        <div class="content">
            @if (TempData["Error"] != null)
            {
                <div class="col-md-12 alert alert-danger">
                    <span><b>Помилка!</b> - @TempData["Error"] </span>
                </div>
            }
            <div class="row">
                <div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Фільтр по категорії</label>
                            @{
                                await Html.RenderPartialAsync("_CategoryDropDownList", Model.CategoryMenu);
                            }
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>&nbsp;</label>
                            <br />
                            <div class="text-center">
                                <button type="submit" class="btn btn-info btn-fill btn-wd" onclick="javascript:return confirm('Увага, після фіксації накладної, її редагкування буде не доступне!');">Фіксувати накладу</button>
                            </div>
                            <div class="clearfix"></div>
                            @*                        <a class="btn btn-info btn-fill btn-wd" asp-controller="Options" asp-action="Product">
                            Створити новий товар
                            </a>
                            *@
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Накладна</label>
                            <br />
                            <div>
                                № @Model.Invoice.Number від @Model.Invoice.Date.ToString("d")
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Постачальник</label>
                            <br />
                            <div>
                                @Model.Invoice.Client.LastName @Model.Invoice.Client.FirstName
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Сума</label>
                            <br />
                            <div>
                                <span id="invoiceSum">@Model.Sum</span> @Model.Invoice.Currency.ShortName
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div>

                        <div class="card">
                            <div class="content">

                                @if (Model.ProductToInvoices == null)
                                {
                                    <div class="text-center">
                                        <div class="card-body">
                                            <h4 class="card-title">Продукція відсутня</h4>
                                        </div>
                                    </div>
                                }
                                else
                                {


                                    <div class="content table-responsive table-full-width">
                                        <table class="table table-striped  text-left">
                                            <thead>
                                                <tr>
                                                    <th>Категорія</th>
                                                    <th>Фірма</th>
                                                    <th>Найменування</th>
                                                    <th>Опис</th>
                                                    <th>Код</th>                                                    
                                                    <th>Кількість</th>
                                                    <th style="text-align:center">Од.Вим.</th>
                                                    <th>Ціна</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>

                                                @foreach (var item in Model.ProductToInvoices)
                                                {
                                                    <tr>
                                                        <td>@item.Product.Category.Name</td>
                                                        <td>@item.Product.Manufacturer.Name</td>
                                                        <td>@item.Product.Name</td>
                                                        <td>@item.Product.Description</td>
                                                        <td>@item.Product.Barcode</td>                                                        
                                                        <td><input type="text" id="Amount_@item.Product.Id" name="Amount_@item.Product.Id" value="@item.Amount" class="form-control border-input" /></td>
                                                        <td style="text-align:center">@item.Product.Unit.Name</td>
                                                        <td><input type="text" id="Price_@item.Product.Id" name="Price_@item.Product.Id" value="@item.Price" class="form-control border-input" /></td>
                                                        @*<td><button type="submit" class="btn btn-info btn-fill btn-wd">Додати</button></td>*@
                                                        <td>
                                                            <input type="hidden" id="Invoice_@item.Product.Id" value="@item.InvoiceId" />
                                                            <a class="btn btn-sm btn-success" id="btn_@item.Product.Id" onClick="insertData(@item.Product.Id);">
                                                                <i class="ti-plus"></i>
                                                            </a>
                                                            <a class="btn btn-sm btn-danger" id="btnDelete_@item.Product.Id" onClick="deleteData(@item.Product.Id);">
                                                                <i class="ti-trash"></i>
                                                            </a>

                                                            @*<input id="btn_@item.Product.Id" onClick="insertData(@item.Product.Id);" type="button" value="Submit" />

                                                    onclick="javascript:return confirm('Видалити?');">
                                                    *@
                                                        </td>
                                                    </tr>
                                                }

                                            </tbody>
                                        </table>
                                    </div>

                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    function insertData(productId) {
        var Amount = document.getElementById('Amount_' + productId).value;
        var Price = document.getElementById('Price_' + productId).value;
        var InvoiceId = document.getElementById('Invoice_' + productId).value;
        var ProductId = productId;

        $.ajax({
            url: "/Invoice/AddProduct",
            data:
            {
                'InvoiceId': InvoiceId,
                'ProductId': ProductId,
                'Amount': Amount,
                'Price': Price
            },
            type: "post",
            cache: false,
            success: function (result) {
                document.getElementById('invoiceSum').textContent = result;
                //alert('Товар додано!');
                demo.showNotification('top', 'center', 'Товар додано!', 'success');
                //$("#hdnOrigComments").val($('#txtComments').val());
                //$('#lblCommentsNotification').text(savingStatus);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                demo.showNotification('top', 'center', 'Введіть значення!', 'warning');
                //$('#lblCommentsNotification').text("Error encountered while saving the comments.");
            }
        });

    };

    function deleteData(productId) {
        //alert("Видалення");

        var Amount = document.getElementById('Amount_' + productId).value;
        var Price = document.getElementById('Price_' + productId).value;
        var InvoiceId = document.getElementById('Invoice_' + productId).value;
        var ProductId = productId;

        $.ajax({
            url: "/Invoice/DeleteProduct",
            data:
            {
                'InvoiceId': InvoiceId,
                'ProductId': ProductId,
                'Amount': Amount,
                'Price': Price
            },
            type: "post",
            cache: false,
            success: function (result) {
                document.getElementById('Amount_' + productId).value = null;
                document.getElementById('Price_' + productId).value = null;
                document.getElementById('invoiceSum').textContent = result;
                demo.showNotification('top', 'center', 'Товар видалено!', 'success');
            },
            error: function (xhr, ajaxOptions, thrownError) {
                demo.showNotification('top', 'center', 'Нема даних для видалення!', 'warning');

                //$('#lblCommentsNotification').text("Error encountered while saving the comments.");
            }
        });

    };


</script>

HSG.Warehouse.Web/Views/Warehouse/Index.cshtml
@model WarehouseViewModel

<form method="post" asp-action="SaveInvoice" enctype="multipart/form-data">
    <div class="card">
        <div class="content">
            @if (TempData["Error"] != null)
            {
                <div class="col-md-12 alert alert-danger">
                    <span><b>Помилка!</b> - @TempData["Error"] </span>
                </div>
            }
            <div class="row">
                <div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Фільтр по категорії</label>
                            @{
                                await Html.RenderPartialAsync("_CategoryDropDownList", Model.CategoryMenu);
                            }
                        </div>
                    </div>

                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div>

                        <div class="card">
                            <div class="content">

                                @if (Model.Warehouse == null)
                                {
                                    <div class="text-center">
                                        <div class="card-body">
                                            <h4 class="card-title">Продукція відсутня</h4>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="content table-responsive table-full-width">
                                        <table class="table table-striped  text-left">
                                            <thead>
                                                <tr>
                                                    <th>Категорія</th>
                                                    <th>Фірма</th>
                                                    <th>Найменування</th>
                                                    <th>Опис</th>
                                                    <th>Код</th>
                                                    <th>Кількість</th>
                                                    <th>Од.Вим.</th>
                                                    <th>Ціна</th>
                                                    <th>Валюта</th>
                                                    <th>Сума</th>
                                                    <th>Мін.Залишок</th>
                                                </tr>
                                            </thead>
                                            <tbody>

                                                @foreach (var item in Model.Warehouse)
                                                {
                                                    <tr>
                                                        <td>@item.Product.Category.Name</td>
                                                        <td>@item.Product.Manufacturer.Name</td>
                                                        <td>@item.Product.Name</td>
                                                        <td>@item.Product.Description</td>
                                                        <td>@item.Product.Barcode</td>
                                                        <td>@item.Amount</td>
                                                        <td>@item.Product.Unit.Name</td>
                                                        <td>@item.Product.Price</td>
                                                        <td>@item.InvoiceDetail.Invoice.Currency.ShortName</td>
                                                        <td>@(item.Amount * item.Product.Price)</td>
                                                        <td>@item.Product.MinimunStock</td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>